name: Docker Image CI

on:
  push:
    branches: [ "foxy" ]
  pull_request:
    branches: [ "foxy" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:  
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
        
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_TOKEN   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_HUB_REPOSITORY:$GITHUB_SHA
      
    - name: Docker Push 
        docker push $DOCKER_USER/$DOCKER_HUB_REPOSITORY:$GITHUB_SHA
